### ISSUE TITLE
Recommend using the Comma cable on port 2 data and any cable on port 1 for power

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/flash#19]
People can have shit cables if they aren't the comma one.

**Comment by adeebshihadeh** [comment]
Not all our OBD-C cables have the data lines, so this won't always work.

**Comment by nelsonjchen** [comment]
Perhaps the language could be adjusted to be more specific? I could say the comma ODB-C cable that comes with the comma three if assuming the "comma two long cable" is what you're referring to as the cable without data lines:

https://comma.ai/shop/obd-c-cable
