### ISSUE TITLE
Recommend less drastic steps first for System Reset at the top

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/flash#25]
Tap tap tap tap tap on boot

Sometimes people don't need to flash AGNOS and the toil and pain isn't worth it.

**Comment by adeebshihadeh** [comment]
Disagree with this. This is the most complete thing a user can do to recover their device, and we should just make it as easy as possible to run. 

> Device doesn't work? Try flash.comma.ai. That didn't work? Open a support ticket.

**Comment by nelsonjchen** [comment]
Ah, I don't know, even your example quote follows a theme of escalation. But I guess with EDL and stuff like that on the horizon making it much easier, maybe omitting the lighter weight System Reset as an initial suggestion is OK.
