### ISSUE TITLE
Deployed version of flash.comma.ai still references sendEvent from "`rm analytics`"

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/flash#27]
Commit `rm analytics`: https://github.com/commaai/flash/commit/9b0b00b36705224e737ce9b7e5edf4fdb5b6476d

Console Error:

<img width="1057" alt="Screenshot_2023-11-13_at_8 08 54_PM" src="https://github.com/commaai/flash/assets/5363/10643260-6028-4b94-994d-c403fcfac7c9">

Minified chunk still has `sendEvent`:

<img width="1512" alt="image" src="https://github.com/commaai/flash/assets/5363/7b30b272-ba2a-4f26-941c-79b4267231f2">

Probably the cause of issues like in #26 . Maybe some top level webpack'd file wasn't deployed correctly.

**Comment by adeebshihadeh** [comment]
Looks like this was some more sendEvent usage (8d9982cc1bdfe04ffc59dee87fb11fd77f811d79). Deploying an update shortly

**Comment by nelsonjchen** [comment]
Pending confirmation from people who are looking to use it/need it in the flashing thread,

**Comment by nelsonjchen** [comment]
https://discord.com/channels/469524606043160576/1138960979384881212/1174375634479357992

![image](https://github.com/commaai/flash/assets/5363/695f464d-e363-4fa9-8e9d-0cb640453f72)
