### ISSUE TITLE
[$200 bounty] Get flash.comma.ai working with GitHub pages

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/flash#31]
We want to move this to Pages, and CNAME from there. Get this building as a static site/app, then setup CI to build/deploy it.

Requirements:
* CI builds the page 
* CI deploys it on master
* GH pages demo on your fork

**Comment by adeebshihadeh** [comment]
@samrum want to try this one?

**Comment by samrum** [comment]
Yeah, I can grab it
