### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by sshane** [commaai/flash#4]
Happens every time on both Chrome and Opera.

![image](https://github.com/commaai/flash/assets/25857203/4a4677f2-4114-4f65-960d-ca51bb7967f0)

![image](https://github.com/commaai/flash/assets/25857203/9a664718-97c9-47ed-8023-cb9e864bd0a9)

**Comment by incognitojam** [comment]
Tested and working

**Comment by sshane** [comment]
Is there some simple CI test we can add for this?
