### ISSUE TITLE
sometimes gets stuck on unpacking system

### ISSUE THREAD

**Issue by sshane** [commaai/flash#6]
![image](https://github.com/commaai/flash/assets/25857203/62aee4ad-8660-44b2-bebd-af0e5028b853)

if it really is in progress and not stuck, it shouldn't say 100%

edit: left here for ~10 minutes, no change in progress

edit: oh I see the progress is for the current step, yeah seems stuck somewhere

https://github.com/commaai/flash/assets/25857203/114045c2-03b5-4b52-b7b5-80bf7eb5a386

edit: hmm, after refreshing and recording that clip above, it passed the unpacking step after maybe 30 seconds at 100% and is now flashing properly

**Comment by incognitojam** [comment]
will add a test for this once the new images are in

**Comment by adeebshihadeh** [comment]
This has been partially rewritten.
